import type { ReactElement } from "react";

import type { ToolData } from "@/data/tool.types";

type Props = {
  tool: ToolData;
};

type CleanFaqItem = {
  question: string;
  answer: string;
};

const SITE_URL = "https://pngjpgconvert.com";
const LANGUAGE = "en";

/**
 * ------------------------------------------------------------------
 * HELPERS
 * ------------------------------------------------------------------
 */

/**
 * Normalize whitespace and remove HTML markup.
 *
 * FAQ JSON-LD should contain clean textual answers rather than
 * arbitrary HTML markup.
 */
function cleanText(
  value: string | undefined,
): string {
  if (!value) {
    return "";
  }

  return value
    .replace(/<[^>]*>/g, " ")
    .replace(/&nbsp;/gi, " ")
    .replace(/&amp;/gi, "&")
    .replace(/&lt;/gi, "<")
    .replace(/&gt;/gi, ">")
    .replace(/\s+/g, " ")
    .trim();
}

/**
 * Normalize a slug safely.
 *
 * Prevents malformed URLs such as:
 * /tool/
 * //tool//
 */
function normalizeSlug(
  slug: string | undefined,
): string {
  if (!slug) {
    return "";
  }

  return slug
    .trim()
    .replace(/^\/+|\/+$/g, "");
}

/**
 * Normalize text used for duplicate detection.
 *
 * Case and whitespace differences should not create
 * duplicate FAQ entities.
 */
function normalizeComparisonText(
  value: string,
): string {
  return value
    .toLowerCase()
    .replace(/\s+/g, " ")
    .trim();
}

/**
 * Remove duplicate FAQ entries while preserving
 * their original order.
 */
function uniqueFaqItems(
  items: CleanFaqItem[],
): CleanFaqItem[] {
  const seen = new Set<string>();

  return items.filter((item) => {
    const key = [
      normalizeComparisonText(item.question),
      normalizeComparisonText(item.answer),
    ].join("::");

    if (seen.has(key)) {
      return false;
    }

    seen.add(key);

    return true;
  });
}

/**
 * ------------------------------------------------------------------
 * FAQ SCHEMA
 * ------------------------------------------------------------------
 */

export default function FAQSchema({
  tool,
}: Props): ReactElement | null {
  /**
   * --------------------------------------------------------------
   * VALIDATE SOURCE DATA
   * --------------------------------------------------------------
   *
   * Never generate FAQ structured data when there is no
   * visible FAQ content.
   */

  if (
    !Array.isArray(tool.faq) ||
    tool.faq.length === 0
  ) {
    return null;
  }

  /**
   * --------------------------------------------------------------
   * CLEAN FAQ CONTENT
   * --------------------------------------------------------------
   *
   * Invalid entries are removed before generating JSON-LD.
   */

  const cleanedFaqs: CleanFaqItem[] =
    tool.faq
      .map((item) => ({
        question: cleanText(item.question),
        answer: cleanText(item.answer),
      }))
      .filter(
        (item) =>
          item.question.length > 0 &&
          item.answer.length > 0,
      );

  /**
   * --------------------------------------------------------------
   * REMOVE DUPLICATES
   * --------------------------------------------------------------
   */

  const uniqueFaqs =
    uniqueFaqItems(cleanedFaqs);

  if (uniqueFaqs.length === 0) {
    return null;
  }

  /**
   * --------------------------------------------------------------
   * CANONICAL URL
   * --------------------------------------------------------------
   */

  const cleanSlug = normalizeSlug(
    tool.slug,
  );

  if (!cleanSlug) {
    return null;
  }

  const pageUrl =
    `${SITE_URL}/${cleanSlug}`;

  /**
   * --------------------------------------------------------------
   * ENTITY IDS
   * --------------------------------------------------------------
   *
   * These IDs allow FAQPage to connect with the
   * WebPage entity generated by ToolSchema.
   */

  const pageId =
    `${pageUrl}#webpage`;

  const faqId =
    `${pageUrl}#faq`;

  /**
   * --------------------------------------------------------------
   * FAQ TITLE / DESCRIPTION
   * --------------------------------------------------------------
   */

  const title =
    cleanText(tool.title) ||
    cleanText(tool.heroTitle) ||
    "Frequently Asked Questions";

  const faqName =
    `${title} - Frequently Asked Questions`;

  const faqDescription =
    `Frequently asked questions about ${title}, including how to use the tool and what to expect from the conversion process.`;

  /**
   * --------------------------------------------------------------
   * QUESTION ENTITIES
   * --------------------------------------------------------------
   *
   * Each question receives a deterministic @id.
   *
   * Example:
   * /png-to-jpg#faq-question-1
   */

  const mainEntity = uniqueFaqs.map(
    ({ question, answer }, index) => {
      const questionId =
        `${pageUrl}#faq-question-${index + 1}`;

      return {
        "@type": "Question",

        "@id": questionId,

        name: question,

        isPartOf: {
          "@id": faqId,
        },

        acceptedAnswer: {
          "@type": "Answer",

          "@id":
            `${questionId}-answer`,

          text: answer,

          isPartOf: {
            "@id": faqId,
          },
        },
      };
    },
  );

  /**
   * --------------------------------------------------------------
   * FAQ PAGE
   * --------------------------------------------------------------
   *
   * FAQPage is explicitly connected to the current WebPage.
   */

  const faqPage = {
    "@type": "FAQPage",

    "@id": faqId,

    url: `${pageUrl}#faq`,

    name: faqName,

    description: faqDescription,

    inLanguage: LANGUAGE,

    isPartOf: {
      "@id": pageId,
    },

    mainEntity,
  };

  /**
   * --------------------------------------------------------------
   * GRAPH
   * --------------------------------------------------------------
   *
   * FAQPage is kept as a separate graph entity while
   * maintaining a stable relationship with ToolSchema.
   *
   * Organization / WebSite / WebPage are intentionally
   * not duplicated here.
   */

  const schema = {
    "@context": "https://schema.org",

    "@graph": [
      faqPage,
    ],
  };

  /**
   * --------------------------------------------------------------
   * JSON-LD OUTPUT
   * --------------------------------------------------------------
   */

  return (
    <script
      type="application/ld+json"
      dangerouslySetInnerHTML={{
        __html: JSON.stringify(schema),
      }}
    />
  );
}

